SELECT 
    ACCOUNT_DIM_ID,
    AVG(DAILY_BALANCE_AMT) AS AVG_DAILY_BALANCE
FROM fact_account_balance
GROUP BY ACCOUNT_DIM_ID;

CREATE TABLE fact_account_balance_avg (
    ACCOUNT_DIM_ID INT,
    AVG_DAILY_BALANCE DECIMAL(15, 2)
);

INSERT INTO fact_account_balance_avg (
    ACCOUNT_DIM_ID,
    AVG_DAILY_BALANCE
)
SELECT 
    ACCOUNT_DIM_ID,
    AVG(DAILY_BALANCE_AMT) AS AVG_DAILY_BALANCE
FROM fact_account_balance
GROUP BY ACCOUNT_DIM_ID;
