SELECT 
    CUSTOMER_DIM_ID, 
    AVG(POLICY_BALANCE_AMT) AS avg_POLICY_BALANCE_AMT, 
    AVG(INSURANCE_POLICY_CASE_SIZE) AS avg_INSURANCE_POLICY_CASE_SIZE
FROM fact_insurance_life
GROUP BY CUSTOMER_DIM_ID;

CREATE TABLE fact_insurance_life_avg (
    CUSTOMER_DIM_ID INT,
    avg_POLICY_BALANCE_AMT DECIMAL(15, 2),
    avg_INSURANCE_POLICY_CASE_SIZE DECIMAL(15, 2)
);

INSERT INTO fact_insurance_life_avg (CUSTOMER_DIM_ID, avg_POLICY_BALANCE_AMT, avg_INSURANCE_POLICY_CASE_SIZE)
SELECT 
    CUSTOMER_DIM_ID, 
    AVG(POLICY_BALANCE_AMT) AS avg_POLICY_BALANCE_AMT, 
    AVG(INSURANCE_POLICY_CASE_SIZE) AS avg_INSURANCE_POLICY_CASE_SIZE
FROM fact_insurance_life
GROUP BY CUSTOMER_DIM_ID;
