CREATE TABLE fact_overdraft_avg (
    ACCOUNT_DIM_ID INT,
    AVG_OVERDRAFT_SPEND DECIMAL(15, 2)
);

INSERT INTO fact_overdraft_avg (
    ACCOUNT_DIM_ID,
    AVG_OVERDRAFT_SPEND
)
SELECT 
    ACCOUNT_DIM_ID,
    AVG(OVERDRAFT_SPEND_AMT) AS AVG_OVERDRAFT_SPEND
FROM fact_overdraft
GROUP BY ACCOUNT_DIM_ID;
