CREATE TABLE FACT_INSURANCE_LIFE (
    DAY_ID DATE,
    CUSTOMER_DIM_ID INT,
    POLICY_ID VARCHAR(20),
    POLICY_BALANCE_AMT DECIMAL(10, 2),
    POLICY_STATUS ENUM('Active', 'Expired'),
    INSURANCE_POLICY_CASE_SIZE DECIMAL(10, 2),
    EFF_DT DATE,
    END_DT DATE,
    PRIMARY KEY (DAY_ID, CUSTOMER_DIM_ID),
    CONSTRAINT FK_INSURANCE_CUSTOMER FOREIGN KEY (CUSTOMER_DIM_ID) REFERENCES DIM_CUSTOMER(CUSTOMER_DIM_ID)
);